### PR TITLE
Adding a basic error view page

### PR DESCRIPTION
**Pull request by j-v-r**
Updated the _.catch()_ handler functions in the route file to redirect to '**/views/error**'. Created a new view page called **error.ejs**. Updated test to expect a redirect to '**/views/error**' instead of '**/**'. Plan implementing a way to handle the error and display more detailed information soon.

### CODE REVIEW

**Comment by eebbesen** [comment]
Nice! 

Run `node_modules/eslint/bin/eslint.js . --ext .js` and see what the results are. You can ignore
* `Unexpected console statement`
* `is not defined` in *_test.js files

**Comment by j-v-r** [comment]
Cool, I'll run that tonight and lint it up.

**Comment by j-v-r** [comment]
Ran this through ESLint. I fixed everything that wasn't:

- `Unexpected console statement`
- `is not defined` in *_test.js files

There were a couple more ESlint warning in the test files, but that wasn't related to any code I touched (indenting mostly), so I left that stuff alone.

**Review by eebbesen — APPROVED** [review]
All unit tests pass

**Pull request merged**
